[package]
name = "float-cmp"
version = "0.7.0-pre"
authors = ["Mike Dilger <mike@mikedilger.com>"]
description = "Floating point approximate comparison traits"
repository = "https://github.com/mikedilger/float-cmp"
documentation = "https://docs.rs/float-cmp"
readme = "README.md"
keywords = [ "float", "comparison", "fuzzy", "approximate" ]
license = "MIT"
edition = "2018"

[lib]
name = "float_cmp"
path = "src/lib.rs"
test = true
doctest = true
doc = true

[features]
default = [ "num-traits", "std" ]
std = []

[dependencies]
num-traits = { version = "0.2", default-features = false, optional = true }
